// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8mZErbXqze_JRo1HcrscGkN0v5fS9lG4',
    appId: '1:196790250714:ios:be0330c3e52e50be8a89e3',
    messagingSenderId: '196790250714',
    projectId: 'elearning-raisa',
    storageBucket: 'elearning-raisa.appspot.com',
    iosBundleId: 'com.example.elearningDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUIFUtzrY5YvhLmGQsl4Vz2IpnA_rNYd8',
    appId: '1:196790250714:web:9f70eec6ec17152d8a89e3',
    messagingSenderId: '196790250714',
    projectId: 'elearning-raisa',
    authDomain: 'elearning-raisa.firebaseapp.com',
    storageBucket: 'elearning-raisa.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUIFUtzrY5YvhLmGQsl4Vz2IpnA_rNYd8',
    appId: '1:196790250714:web:18a05fd86e013c708a89e3',
    messagingSenderId: '196790250714',
    projectId: 'elearning-raisa',
    authDomain: 'elearning-raisa.firebaseapp.com',
    storageBucket: 'elearning-raisa.appspot.com',
  );

}